fail_fast: true

repos:
  - repo: local
    hooks:
      - id: just-bootstrap
        name: Bootstrap just
        language: rust
        types: [rust]
        entry: |
          bash -c '
            if ! cargo-binstall -V >/dev/null 2>&1; then
              echo "Installing cargo-binstall..."
              curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
            fi
            if ! just -V >/dev/null 2>&1; then
              echo "Installing just..."
              cargo binstall --no-confirm just
            fi
          '
        pass_filenames: false
        always_run: true
