fail_fast: false

repos:
  - repo: https://github.com/lmmx/just-pre-commit
    rev: v0.2.7
    hooks:
      - id: ensure-just-system
        args: ['hello']
      - id: ensure-just-script
        args: ['hello']
