fail_fast: false

repos:
  - repo: https://github.com/lmmx/just-pre-commit
    rev: v0.3.2
    hooks:
      - id: ensure-just-system
        args: ['code-quality']
      - id: ensure-just-script
        args: ['code-quality']
