fail_fast: true

repos:
  - repo: local
    hooks:
      - id: just-bootstrap
        name: Bootstrap just
        language: system
        entry: pip install rust-just
        pass_filenames: false
        always_run: true
