fail_fast: false

repos:
  - repo: https://github.com/lmmx/just-pre-commit
    rev: v0.3.12
    hooks:
      - id: run-just-script
        args: ['code-quality']
      # - id: run-just-rust
      #   args: ['code-quality']
