[dependencies]
clap = {version = "4.5.37", features = ["derive"]}
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
thiserror = "2.0.12"

[package]
name = "isotarp"
version = "0.1.0"
edition = "2024"
